server:
  compression:
    enabled: true
  port: ${PORT:8091}
  servlet:
    context-path: /api/fullstack/test/

spring:
  application:
    name: sirio-full-stack-developer
  output:
    ansi:
      enabled: always
  banner:
    location: classpath:/config/banner/api-sirio-fullstack-developer.txt

  jpa:
    open-in-view: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  datasource:
    url: jdbc:mysql://${HOST:localhost}:${PORT:3306}/${DATABASE:sirio}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${USR:root}
    password: ${PSW:toor}
    driver-class-name: ${DRIVER:com.mysql.cj.jdbc.Driver}

# SECRET_KEY
sirio-full-stack-developer:
  security:
    token:
      secret: ${JWT_SECRET:secret-key}