CREATE TABLE usuarios(
  id BIGINT(36) NOT NULL AUTO_INCREMENT,
 	email VARCHAR(50) NOT NULL UNIQUE,
 	senha VARCHAR(150) NOT NULL,
 	perfil VARCHAR(20) NOT NULL,
 	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;