CREATE TABLE usuarios(
  id BIGINT(20) NOT NULL,
 	nome VARCHAR(40) NOT NULL,
 	email VARCHAR(50) NOT NULL UNIQUE,
 	senha VARCHAR(150) NOT NULL,
 	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;